language: node_js
node_js:
  - "6"
  - "5"
  - "4"
sudo: false
before_script:
  - npm install
  - npm run init
  - npm run build
script:
  - npm run test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
    - CXX=g++-4.8
